AllCops:
  Includes:
    - 'Rakefile'
    - 'Gemfile'
  Excludes:
    - tmp/**/**/**/**

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 90
  Exclude:
    - 'Gemfile'
    - 'cybele.gemspec'

Style/AccessorMethodName:
  Exclude:
    - 'lib/cybele/generators/app_generator.rb'

Metrics/MethodLength:
  CountComments: false
  Max: 15

Metrics/BlockLength:
  CountComments: false
  Max: 40
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'lib/cybele/app_builder.rb'
    - 'lib/cybele/generators/app_generator.rb'

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed

Style/IndentHeredoc:
  Exclude:
    - 'spec/features/cli_help_spec.rb'
