AllCops:
  Include:
    - 'Rakefile'
    - 'Gemfile'
  Exclude:
    - tmp/**/**/**/**

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 110
  Exclude:
    - 'Gemfile'
    - 'cybele.gemspec'

Metrics/ClassLength:
  Exclude:
    - 'lib/cybele/generators/app_generator.rb'

Naming/AccessorMethodName:
  Exclude:
    - 'lib/cybele/generators/app_generator.rb'

Metrics/MethodLength:
  CountComments: false
  Max: 15

Metrics/BlockLength:
  CountComments: false
  Max: 40
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'lib/cybele/app_builder.rb'
    - 'lib/cybele/generators/app_generator.rb'

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed
  Exclude:
    - 'templates/error_pages/**/*.rb'

Layout/IndentHeredoc:
  Exclude:
    - 'spec/features/cli_help_spec.rb'

Naming/HeredocDelimiterNaming:
  Exclude:
    - 'spec/features/cli_help_spec.rb'
    - 'spec/features/git_and_git_flow_spec.rb'

Layout/InitialIndentation:
  Exclude:
    - 'templates/error_pages/**/*.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'templates/app_files/app/controllers/**/*.rb'