AllCops:
  Include:
    - 'Rakefile'
    - 'Gemfile'
  Exclude:
    - tmp/**/**/**/**

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 110
  Exclude:
    - 'Gemfile'
    - 'cybele.gemspec'

Metrics/ClassLength:
  Exclude:
    - 'spec/support/gem_test_helpers.rb'
    - 'lib/cybele/generators/app_generator.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/support/gem_test_helpers.rb'

Style/AccessorMethodName:
  Exclude:
    - 'lib/cybele/generators/app_generator.rb'

Metrics/MethodLength:
  CountComments: false
  Max: 15
  Exclude:
    - 'spec/support/gem_test_helpers.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/support/gem_test_helpers.rb'
    - 'spec/support/mail_test_helpers.rb'

Metrics/BlockLength:
  CountComments: false
  Max: 40
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'lib/cybele/app_builder.rb'
    - 'lib/cybele/generators/app_generator.rb'
    - 'spec/support/cybele_test_helpers.rb'

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed

Style/IndentHeredoc:
  Exclude:
    - 'spec/features/cli_help_spec.rb'

Naming/HeredocDelimiterNaming:
  Exclude:
    - 'spec/features/cli_help_spec.rb'