AllCops:
  Includes:
    - 'Rakefile'
    - 'Gemfile'
  Excludes:
    - bin/**
    - spec/**/**/**/**
    - test/**/**/**/**
    - tmp/**/**/**/**

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 90
  Exclude:
    - 'Gemfile'
    - 'cybele.gemspec'

Style/AccessorMethodName:
  Exclude:
    - 'lib/cybele/generators/app_generator.rb'

Metrics/MethodLength:
  CountComments: false
  Max: 15
  Exclude:
    - 'lib/cybele/app_builder.rb'

Metrics/BlockLength:
  CountComments: false
  Max: 40
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed
